### ISSUE TITLE
Use requests' parameter handling instead of building the URL yourself

### ISSUE THREAD

**Issue by reinout** [nens/threedi-scenario-downloader#4]
URL-escapen van waardes: dat soort zaken gebeurd niet als je zelf een URL samenstelt met `.format()`.
Je kan alles achter de `?` door requests laten doen, dat is netter en veiliger:
http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls

Wat er nu staat:

    url = "{}scenarios/?model_name__icontains={}&limit={}".format(....)
    requests.get(url)

Dat zou dan zoiets worden:

    url = "{}scenarios/".format(....)
    requests.get(url, params={"model_name__icontains": "pietje", "limit": 10})

**Comment by emielverstegen** [comment]
is bij #7 opgepakt
