### ISSUE TITLE
Docstrings minder breed maken. En de juiste stijl aanhouden :-)

### ISSUE THREAD

**Issue by reinout** [nens/threedi-scenario-downloader#5]
De docstrings van de functies zijn nu vaak laaaaaaaaaaaaaaaaaaaaaaaaang. "Black" herformatteert die niet, maar ze zijn toch echt wel te lang.

Docstrings zijn of één regel, of ze zijn een regel + lege regel + verdere tekst.
De eerste regel moet een "bevel" zijn. Dus `return aantal bloemkolen` i.p.v. beschrijvend zoals `returns aantal bloemkolen`.
Heel kort zeggen wat een functie teruggeeft is altijd handig. Dat dwingt jezelf ook om het doel van de functie duidelijk te krijgen.
Zoiets als de `clear_inbox()` functie geeft niets terug. Prima. `Remove messages from the inbox` geeft netjes aan dat er niets wordt teruggegeven.

De langere versie: https://www.python.org/dev/peps/pep-0257/

**Comment by emielverstegen** [comment]
Meegenomen in laatste commit
